### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by Bisaloo**
Should fix https://github.com/epiverse-trace/cleanepi/issues/163 for the most part. In total, this allows a ~20x speedup.

I'll likely propose a C implementation of `number_from()` in a couple of weeks for fun and as an exercise. It won't need to be merged and can live as an alternative branch for users with high performance need & a C compiler.

### `main` version

``` r
library(rio)
library(cleanepi)

covid <- rio::import(
  "https://raw.githubusercontent.com/Joskerus/Enlaces-provisionales/main/data_limpieza.zip",
  which = "datos_covid_LA.RDS"
) |> 
  cleanepi::standardize_column_names()
#> Warning: The `trust` argument of `import()` should be explicit for serialization formats
#> as of rio 1.0.3.
#> ℹ Missing `trust` will be set to FALSE by default for RDS in 2.0.0.
#> ℹ The deprecated feature was likely used in the rio package.
#>   Please report the issue at <https://github.com/gesistsa/rio/issues>.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.

tictoc::tic()
test <- numberize::numberize(covid$numero_de_hospitalizaciones_recientes, lang = "es")
tictoc::toc()
#> 73.346 sec elapsed
```

<sup>Created on 2024-07-27 with [reprex v2.1.1](https://reprex.tidyverse.org/)</sup>

### proposed version

``` r
library(rio)
library(cleanepi)

covid <- rio::import(
  "https://raw.githubusercontent.com/Joskerus/Enlaces-provisionales/main/data_limpieza.zip",
  which = "datos_covid_LA.RDS"
) |> 
  cleanepi::standardize_column_names()
#> Warning: The `trust` argument of `import()` should be explicit for serialization formats
#> as of rio 1.0.3.
#> ℹ Missing `trust` will be set to FALSE by default for RDS in 2.0.0.
#> ℹ The deprecated feature was likely used in the rio package.
#>   Please report the issue at <https://github.com/gesistsa/rio/issues>.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
#> generated.

tictoc::tic()
test <- numberize::numberize(covid$numero_de_hospitalizaciones_recientes, lang = "es")
tictoc::toc()
#> 3.088 sec elapsed
```

<sup>Created on 2024-07-27 with [reprex v2.1.1](https://reprex.tidyverse.org/)</sup>

### CODE REVIEW

**Comment by avallecam** [comment]
> Should fix [epiverse-trace/cleanepi#163](https://github.com/epiverse-trace/cleanepi/issues/163) for the most part. In total, this allows a ~20x speedup.

👍 running the proposed version took me `4.25 sec elapsed`. Only after installing `pak::pak("epiverse-trace/numberize@improve-performance")` I needed to restart R to make this work.

**Comment by Bisaloo** [comment]
@bahadzie, would you be able to take care of the conflicts in this PR? Let me know if you've tried and gotten stuck, and I can give it a look myself.

**Comment by bahadzie** [comment]
@Bisaloo  there a lot of other changes that were implemented as a result of the full package review during CRAN submission that is causing 6 tests currently in main to fail.

In my opinion our options are 
1. rebase the PR on main and fix the merge conflicts
2. implement the performance improvements from a new PR branching of main

What's your preference?

**Comment by Bisaloo** [comment]
> In my opinion our options are
> 
>     1. rebase the PR on main and fix the merge conflicts
> 
>     2. implement the performance improvements from a new PR branching of main
> 
> 
> What's your preference?

If you're taking care of it, I don't have a preference. Both solutions are valid and will lead to the same result.

**Comment by bahadzie** [comment]
I will take care of it.

**Comment by Bisaloo** [comment]
Superseded by #15

**Pull request closed without merging**
